main: com.mortuusterra.MortuusTerraCore
name: MortuusTerraCore
version: 1.0
author: kadeska233
depends: []
softdepend: []
database: false
description: >
             The core plugin for the Mortuus Terra survival server.
             Additional Modules:
             There are many additional modules to add functionality to Mortuus Terra.
             Features:
                 - Radiation
                   - Decreasing Radiation Over Time
                   - Geiger Counters
                   - Nuclear Weather Effects
                   - Rad Suits
                   - GECKs (Radiation Shields)
                   - Craters
                 - Player-Crafted Nukes
                 - Fallout Shelters
                 - World Bordering
                 - Spawn Control
commands:
  supplydrop:
    usage: /supplydrop
    description: Use /supplydrop for help.